In [1]:
import numpy as np
import pandas as pd
import os
import sys
from pathlib import Path

In [2]:
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))

if project_root not in sys.path:
    sys.path.append(project_root)

In [3]:
from mlp_model.mlp import MLP
from mlp_model.layers.hidden import Hidden
from mlp_model.layers.output_layer import OutputLayer
from mlp_model.optimizers.sgd import SGDOptimizer
from mlp_model.losses.mse_loss import MSELoss
from mlp_model.activations.relu import ReLU
from mlp_model.initialize_weights.xavier import XavierInitializer
from trainer.trainer import MLPTrainer

In [4]:
data_kind = "simple" # simple, three_gauss
data_count = 100 # 100, 500, 1000, 10000

train_filepath = Path(project_root) / "data/classification/train" / f"data.{data_kind}.train.{data_count}.csv"

In [5]:
df = pd.read_csv(train_filepath)
df.head(5)

          x         y  cls
0  0.657740  0.104257    1
1 -0.603637 -0.437627    2
2  0.984316 -0.708402    1
3  0.144840  0.087581    1
4  0.381276  0.725078    1

In [6]:
df.shape

(100, 3)

In [7]:
df.describe()

                x           y         cls
count  100.000000  100.000000  100.000000
mean     0.027790    0.034718    1.470000
std      0.620972    0.559405    0.501614
min     -0.986022   -0.988961    1.000000
25%     -0.513825   -0.370448    1.000000
50%     -0.015077   -0.047742    1.000000
75%      0.619693    0.526974    2.000000
max      0.997126    0.996458    2.000000

In [8]:
x = df.drop(["cls"], axis=1)
y = df["cls"].to_numpy().reshape(-1, 1)

In [9]:
mlp = MLP(
    [
        Hidden(2, 16, ReLU()),
        Hidden(16, 16, ReLU()),
        OutputLayer(16, 1)
    ]
)
mlp.initialize_weights(XavierInitializer())

sgd = SGDOptimizer(mlp, 0.01)

In [10]:
trainer = MLPTrainer(mlp, sgd, MSELoss(), 50, 32)
trainer.cross_validate(x, y, 5)

Fold 1: loss = 0.095710
Fold 2: loss = 0.106402
Fold 3: loss = 0.094086
Fold 4: loss = 0.062263
Fold 5: loss = 0.088988
---------------------------------------------------------------

Cross validation with 5 folds results:
Mean loss: 0.08948967855693091
Std loss: 0.014747120043251577

{'folds': [{'fold': 1,
   'val_loss': 0.09570979742377292,
   'history': {'train_loss': [1.7696232122846502,
     1.4117030968822237,
     1.1264898670363235,
     0.8784426565351049,
     0.6947718520889516,
     0.544384795509752,
     0.4352506678282794,
     0.3513264049646903,
     0.29296634937742383,
     0.24484448276075027,
     0.20726945043573103,
     0.18225652087090535,
     0.16218161111674784,
     0.15025677387406483,
     0.1407858834260279,
     0.13324229222861095,
     0.12796581453355702,
     0.12233903909235702,
     0.11785854264274702,
     0.11416785753407403,
     0.11103323111529036,
     0.10788025706056019,
     0.10511122202579393,
     0.10295604425343341,
     0.10068968767074113,
     0.09874490574942284,
     0.09716915095116156,
     0.09543318134796173,
     0.09378166189419837,
     0.0922947914507763,
     0.09089199878119122,
     0.08960345108296378,
     0.08842700359070446,
     0.08720796434659672,
     0.08608510451513984,
     0.0851215302975922,
     0.08422309499700595,
     0.0833902336432414,
     0.08265234065205633,
     0.08200099942700234,
     0.08129326452784802,
     0.0805963080248125,
     0.07994415612606029,
     0.07925546521709309,
     0.07870717413696042,
     0.0781580339085451,
     0.07763915896794313,
     0.07718906591139225,
     0.07671672043396074,
     0.07629371998404103],
    'val_loss': [1.733006776548807,
     1.3864648500220593,
     1.1082976367900383,
     0.8682037299320566,
     0.6880215969225847,
     0.5418138435278791,
     0.43584017369418493,
     0.3547054055142792,
     0.29859569081972565,
     0.2527982745525963,
     0.21731212937382974,
     0.19393079149492792,
     0.17534275140270253,
     0.1643489975242498,
     0.15568112458275785,
     0.14892584189532665,
     0.14417119231245784,
     0.13916780102752527,
     0.13513295230747507,
     0.13184212632150388,
     0.12892452433791546,
     0.12604011700922585,
     0.1234806872458996,
     0.12145203067403723,
     0.11934560712583822,
     0.11747866257186282,
     0.11596435367045566,
     0.11436640874964803,
     0.1128629736417232,
     0.11143589437821053,
     0.11005959329155206,
     0.10880601779858282,
     0.10770434842761359,
     0.10653801751825734,
     0.10560612942338624,
     0.10465647390592339,
     0.1037564250372012,
     0.1029242223049284,
     0.10224060223885927,
     0.10164585562519904,
     0.1009179490629633,
     0.10021907685085726,
     0.09952897523903972,
     0.09884920571745351,
     0.09828130780489067,
     0.09771759372468289,
     0.09712695248263384,
     0.09665295171758166,
     0.09615349064591104,
     0.09570979742377292],
    'batch_loss': [1.9369919323245333,
     2.198485613814164,
     2.158440571371629,
     1.9021342068705478,
     1.5402677792805755,
     1.465089031700352,
     1.4089668105693272,
     1.4896394224160439,
     0.8606408563445798,
     0.9719526535837977,
     1.038701374515174,
     1.2701912650006877,
     0.9204561638256548,
     0.8252480148059762,
     0.6407585050782767,
     0.7584105617461114,
     0.5400915339263683,
     0.6670925280239663,
     0.502315952014981,
     0.6170108154265852,
     0.3281084104613403,
     0.42109486330004686,
     0.45197598624482127,
     0.3109449541813787,
     0.43606854081238833,
     0.3300201661219345,
     0.14229863872043302,
     0.310855011613582,
     0.25350622904865633,
     0.2682341826160876,
     0.21178318213285013,
     0.19772763502870494,
     0.35324715728403855,
     0.25427499904474327,
     0.15169926601899417,
     0.18995398020701904,
     0.1420484847288732,
     0.1910957065497715,
     0.2188740314482871,
     0.15511201618546436,
     0.18340649667883324,
     0.117423859784632,
     0.12475687543710268,
     0.16133057240163698,
     0.16636796950163715,
     0.14321379522648392,
     0.14959749810921633,
     0.1083593696504235,
     0.13137713074610585,
     0.1211403157964694,
     0.1559913810685434,
     0.123555568059735,
     0.10983754868715102,
     0.16572390082471256,
     0.1270670447943728,
     0.10153256374302591,
     0.15017608217851286,
     0.12236162769006864,
     0.12906985063323148,
     0.08148772223373446,
     0.11685936946825703,
     0.1090467599696909,
     0.11684723417139703,
     0.07679341395829531,
     0.11328619101499542,
     0.1711095734226971,
     0.106891237476932,
     0.10529010033517597,
     0.11206421800971136,
     0.11236648559077336,
     0.10035511946206617,
     0.09779374442104927,
     0.12372936332167686,
     0.07635480613941628,
     0.11190652155340482,
     0.09659262674120413,
     0.10264347308663638,
     0.10309049251519507,
     0.10185750795465454,
     0.1085107416846122,
     0.07445830859272143,
     0.07633291426687625,
     0.11910346419941595,
     0.09306034775008687,
     0.09268140487339568,
     0.10789183739132355,
     0.07435375890032564,
     0.10624290897798205,
     0.07788364599784012,
     0.09917036440816512,
     0.06548239540371617,
     0.09234939244590645,
     0.1444182834917731,
     0.06696378408508338,
     0.10811118083401272,
     0.10393116386628473,
     0.06001468752493719,
     0.10060911189396744,
     0.12620583299090873,
     0.08345048461792846,
     0.08126858470773979,
     0.11208794359193835,
     0.06870025295966257,
     0.08187902291634833,
     0.13493194144225013,
     0.10478786825733163,
     0.08101127931849073,
     0.058563639017345445,
     0.08553818766536542,
     0.08766364760413628,
     0.07826431269504878,
     0.06688229118564964,
     0.10622734329175494,
     0.07454047957910406,
     0.09097610163184472,
     0.079406786865855,
     0.076037036674231,
     0.08492829181488644,
     0.08115636828607622,
     0.08267723408830671,
     0.09052832249901475,
     0.08552620480097153,
     0.060195920488010236,
     0.07908370831959008,
     0.0733035450107114,
     0.10291098175526378,
     0.08161244428079872,
     0.08293204571398557,
     0.0737600430315537,
     0.0808610622220016,
     0.0666898497568151,
     0.10433070343369527,
     0.07529018331878981,
     0.0804407994175093,
     0.08465198804288396,
     0.06088460452654672,
     0.07659320348464006,
     0.11858625855912358,
     0.08689335059540487,
     0.07472735885751582,
     0.06826544726613266,
     0.07546171867438278,
     0.08330123098734812,
     0.0704057035778651,
     0.060261183911276585,
     0.08410577429206634,
     0.09778739855428087,
     0.0627915534179549,
     0.10349476801719334,
     0.05189456270336518],
    'weights': [[array([[ 9.93774898e-02,  5.31072561e-01, -4.35283343e-01,
              -5.04502768e-01, -2.05455351e-01, -3.32944046e-01,
               3.99115408e-01,  3.86114898e-01, -3.82050153e-02,
              -4.61532570e-01,  4.91189567e-01, -1.31872203e-01,
               4.21246670e-04, -5.07655923e-01,  5.58215505e-01,
               2.56664945e-01],
             [ 2.87841501e-01, -1.83547524e-01,  2.59232126e-01,
               4.95369615e-01,  2.01760576e-01, -5.50591472e-01,
              -2.66310886e-04,  4.72001413e-01,  2.65673614e-01,
              -3.59745014e-01,  4.02043321e-02, -6.61859956e-02,
              -9.44031039e-02,  4.39101885e-02, -6.92618372e-03,
              -4.59083134e-01]]),
      array([[-6.02929946e-02,  3.30540332e-01,  3.03131465e-02,
              -3.30925434e-02,  3.56607457e-01,  3.34234390e-01,
               2.52889421e-01,  4.11465674e-01,  3.13020490e-01,
              -1.69911070e-01,  1.92960036e-01, -7.36954004e-02,
               4.56663602e-02,  2.35020470e-01, -1.49883560e-01,
              -1.14398838e-01],
             [-4.12070536e-03, -2.52465904e-01,  1.47773360e-01,
              -1.81496377e-01,  3.44263269e-01,  2.51297085e-01,
               4.14450428e-01, -1.56687510e-01, -1.07697842e-02,
               2.82029661e-02, -4.24928038e-01,  3.43597471e-01,
              -4.19783772e-01,  3.41241736e-01,  3.57714016e-01,
               4.00524410e-01],
             [-1.65905726e-01,  3.57474903e-01, -1.80899071e-01,
               4.35014324e-02,  3.97093596e-01, -3.54978700e-01,
              -1.54398772e-01, -2.40551264e-01, -1.37873077e-01,
               1.60121034e-02,  2.78936041e-01,  2.86814179e-02,
               2.83940665e-02,  3.27048823e-01, -3.89530156e-01,
              -1.89204804e-01],
             [-2.36358806e-01,  9.29207520e-02, -3.32000058e-01,
              -7.14229246e-02,  2.24277384e-01, -4.25363351e-01,
               5.04738131e-02, -3.57998296e-01,  3.37867790e-01,
              -2.94971896e-02,  2.90225855e-01,  1.97690976e-01,
               3.42927882e-01, -4.14666248e-01, -8.56473185e-02,
              -3.49682520e-01],
             [-9.30505061e-04,  2.26546514e-01,  1.32890346e-01,
              -3.55800317e-01, -3.66035426e-01,  2.42753619e-01,
              -1.46635873e-01,  3.53392093e-01, -1.10182730e-01,
              -1.10317412e-01,  1.88210195e-01, -3.09772461e-01,
              -3.78607130e-01,  3.07643341e-01,  4.29160277e-01,
              -1.93033359e-01],
             [-2.91373538e-02, -2.20690166e-03,  2.23781430e-04,
              -7.07546024e-02, -3.20837514e-02, -3.17745754e-01,
               1.90979072e-01,  1.38842650e-01, -3.45628451e-01,
              -1.40311844e-01,  4.13567091e-01,  2.87960532e-01,
              -3.04650298e-01,  1.69230124e-01, -4.09006877e-01,
              -1.97487929e-01],
             [ 7.05123719e-02,  1.86642948e-01,  1.21568552e-01,
               6.42847252e-02,  2.35179091e-01, -3.20650643e-01,
              -1.13551008e-01,  3.63777099e-01,  2.11386431e-01,
               9.02415948e-02,  2.87842542e-02,  3.92328941e-01,
               3.32501000e-01,  3.57435906e-02,  2.16202321e-01,
               2.37463088e-01],
             [-2.32359739e-01, -1.50112365e-01, -1.73566475e-01,
              -1.22213308e-02,  1.68504656e-01, -3.31229686e-01,
               2.19136063e-02, -1.92913785e-01,  3.29691279e-01,
               1.08300887e-01, -7.09943591e-02,  3.25432349e-01,
               1.08461458e-01, -2.69433905e-01, -3.31195926e-01,
              -3.32086936e-01],
             [ 1.09799361e-01, -2.02008022e-02, -3.65657155e-01,
               3.07388753e-01,  2.25422289e-01,  3.52337771e-01,
              -2.04736812e-01, -2.90027792e-01, -6.73582769e-02,
               2.26034175e-01, -3.87091915e-01, -1.52054290e-01,
               1.25828340e-01,  1.70708941e-01,  2.00646150e-02,
               8.87719707e-02],
             [-3.82560288e-01, -4.18512335e-01,  1.49359046e-01,
              -1.40313953e-01,  2.58722417e-01,  1.63028486e-01,
               1.65094357e-01, -1.19277611e-01, -3.23681357e-01,
              -2.00631180e-01,  2.47064029e-01,  2.69565724e-01,
              -6.06135782e-02, -3.41575841e-01,  4.23440075e-01,
              -4.27200454e-01],
             [-3.32062366e-01, -1.07068171e-01,  1.79403437e-01,
               2.84600272e-01,  1.45380414e-01, -1.07649563e-01,
              -1.35471777e-01,  3.60278082e-01, -8.16637422e-03,
              -2.03994498e-01,  5.01288551e-02, -8.87547876e-03,
              -4.23423919e-01, -4.14746557e-01, -1.72873853e-01,
               3.16996798e-01],
             [-1.48458560e-01, -2.47353941e-01, -1.03407367e-01,
              -2.15927043e-01,  1.95110729e-01, -1.39915941e-02,
              -1.86852590e-01,  3.93914575e-01,  6.31758056e-02,
               2.35131766e-01,  3.26634588e-01,  1.37445383e-01,
              -1.94123365e-01, -5.81259070e-02,  8.70769621e-03,
              -3.48127624e-01],
             [-2.80587599e-01, -8.46633936e-02, -5.77562236e-02,
               1.68537948e-01,  2.87432263e-01,  3.97684503e-01,
              -3.50535596e-02,  6.56544011e-02, -1.60443393e-01,
              -3.82441121e-01, -2.89124023e-01,  2.52985912e-01,
               3.63731395e-01,  2.99670851e-01,  1.34862469e-01,
               3.02242461e-01],
             [ 3.71421492e-01, -2.69145281e-01,  4.21882438e-01,
               3.97489125e-01, -1.90330862e-01,  2.84940968e-01,
               3.93909904e-01, -2.60268732e-01, -2.30479071e-01,
              -3.11667869e-01, -1.33871885e-01, -3.33703961e-01,
               3.90632886e-01,  6.45424580e-02,  7.63587856e-02,
               3.84286815e-01],
             [-3.07133527e-01, -3.02220804e-01, -4.19430857e-01,
              -3.68894952e-03, -2.45584721e-01,  3.12554112e-01,
              -2.66381044e-01,  3.11538619e-01, -1.20396670e-01,
              -1.90024034e-01,  3.25710832e-01, -9.37477005e-02,
               3.36080609e-01,  2.24567680e-02,  2.47875215e-01,
              -3.79199309e-01],
             [ 1.68442041e-01, -6.88077766e-02,  2.95184609e-01,
              -3.00017618e-01,  4.17362110e-01,  3.54788894e-01,
               2.83945870e-01,  3.66677613e-01,  2.90057483e-01,
              -5.09281443e-02,  1.22583918e-01, -1.49722924e-01,
              -3.16844842e-01,  2.41578849e-01,  2.33053038e-01,
               2.66062568e-01]]),
      array([[-0.1853328 ],
             [ 0.40258742],
             [ 0.48695639],
             [ 0.2840899 ],
             [-0.41418262],
             [-0.2423138 ],
             [-0.10906956],
             [-0.06523485],
             [ 0.11153258],
             [ 0.16359012],
             [ 0.2853389 ],
             [ 0.21676913],
             [ 0.19089518],
             [ 0.20182649],
             [ 0.49751607],
             [ 0.29170444]])],
     [array([[ 0.09715869,  0.53026227, -0.43152034, -0.50286388, -0.21011932,
              -0.33389611,  0.40358832,  0.38491249, -0.0381556 , -0.46400801,
               0.49048982, -0.13069061,  0.00148161, -0.5126419 ,  0.55913413,
               0.25707907],
             [ 0.2871906 , -0.18742266,  0.26178629,  0.49706543,  0.20071082,
              -0.5514743 , -0.00209472,  0.47254156,  0.26400937, -0.36308746,
               0.03963653, -0.06626587, -0.09227222,  0.04202985, -0.00433736,
              -0.46042666]]),
      array([[-0.06029299,  0.33115386,  0.03036621, -0.03173185,  0.35461176,
               0.33402455,  0.25274746,  0.41123676,  0.31355894, -0.16988543,
               0.19434412, -0.0727612 ,  0.04654703,  0.2351139 , -0.14947785,
              -0.11423281],
             [-0.00412071, -0.25246323,  0.150936  , -0.18052151,  0.3402343 ,
               0.24940142,  0.41371626, -0.15730017, -0.00976962,  0.02820297,
              -0.42218663,  0.34578658, -0.41922733,  0.34251093,  0.36161431,
               0.40270754],
             [-0.16590573,  0.35887324, -0.17809587,  0.04521509,  0.39309244,
              -0.35505367, -0.15541447, -0.24057844, -0.13760568,  0.01602882,
               0.28176952,  0.03024976,  0.03013244,  0.32742057, -0.38795877,
              -0.1892048 ],
             [-0.23635881,  0.09506858, -0.32936722, -0.06896609,  0.21945766,
              -0.42536335,  0.04931937, -0.35804286,  0.33833905, -0.02946127,
               0.29363182,  0.1994446 ,  0.34515311, -0.41427164, -0.08419437,
              -0.34968252],
             [-0.00093051,  0.22742398,  0.13400202, -0.35478368, -0.36803444,
               0.24275311, -0.14711472,  0.3533735 , -0.10998977, -0.11030278,
               0.1896237 , -0.30903912, -0.37768476,  0.30780612,  0.42978719,
              -0.19303336],
             [-0.02913735, -0.0022069 ,  0.00853055, -0.07015395, -0.03911707,
              -0.31994065,  0.1891623 ,  0.13828194, -0.34547189, -0.14031184,
               0.41860841,  0.29178335, -0.30336936,  0.17128144, -0.40253674,
              -0.19666214],
             [ 0.07051237,  0.18671944,  0.12333544,  0.06540706,  0.2321014 ,
              -0.32183012, -0.1139768 ,  0.36331105,  0.2122011 ,  0.09024642,
               0.03087953,  0.39400116,  0.33317415,  0.03644423,  0.21861653,
               0.23877696],
             [-0.23235974, -0.14939715, -0.17314542, -0.00960231,  0.16440238,
              -0.3319102 ,  0.02167216, -0.19346628,  0.33083573,  0.10834564,
              -0.0681694 ,  0.3275739 ,  0.11012037, -0.26923818, -0.32985136,
              -0.3314729 ],
             [ 0.10979936, -0.01942694, -0.36558322,  0.30851677,  0.22380032,
               0.35226767, -0.20493085, -0.29015513, -0.06697963,  0.22605626,
              -0.38596122, -0.15142652,  0.12658241,  0.17082722,  0.02026764,
               0.08881372],
             [-0.38256029, -0.41827308,  0.15675295, -0.13933453,  0.2521226 ,
               0.1615342 ,  0.16338691, -0.11966051, -0.32364881, -0.20063118,
               0.25178227,  0.2730141 , -0.05897033, -0.34009668,  0.42875526,
              -0.42695207],
             [-0.33206237, -0.1069509 ,  0.18134532,  0.28607278,  0.14165491,
              -0.1089982 , -0.13594755,  0.35971507, -0.00716423, -0.20398512,
               0.05266143, -0.00685225, -0.42253594, -0.4139802 , -0.17012149,
               0.31848074],
             [-0.14845856, -0.24724405, -0.1016432 , -0.21562662,  0.1934695 ,
              -0.0143003 , -0.18727757,  0.39383533,  0.06318772,  0.23513177,
               0.32780604,  0.13827429, -0.1936637 , -0.05779998,  0.00992396,
              -0.34810393],
             [-0.2805876 , -0.08466339, -0.05675521,  0.16854787,  0.2865988 ,
               0.39729621, -0.03526885,  0.06555503, -0.16037846, -0.38244112,
              -0.28853476,  0.25343893,  0.36378737,  0.30001714,  0.1357618 ,
               0.30249486],
             [ 0.37142149, -0.26814089,  0.42675828,  0.39907621, -0.19566945,
               0.28439829,  0.39252533, -0.26040828, -0.23031006, -0.31166787,
              -0.13007421, -0.33129587,  0.39253884,  0.06531537,  0.07947075,
               0.38428682],
             [-0.30713353, -0.30212051, -0.41697747, -0.0021557 , -0.24982283,
               0.31091906, -0.2669727 ,  0.31089648, -0.11927565, -0.19001784,
               0.32859291, -0.09144562,  0.33699813,  0.02342981,  0.25121985,
              -0.37737749],
             [ 0.16844204, -0.06880778,  0.29978276, -0.29997181,  0.41347043,
               0.35253985,  0.28294541,  0.36610107,  0.29063569, -0.05092814,
               0.12529895, -0.14760539, -0.31684004,  0.24345348,  0.23780145,
               0.26805506]]),
      array([[-0.1853328 ],
             [ 0.40397288],
             [ 0.49362946],
             [ 0.28594843],
             [-0.39578645],
             [-0.2384972 ],
             [-0.09752015],
             [-0.0546874 ],
             [ 0.11771232],
             [ 0.1635927 ],
             [ 0.30301253],
             [ 0.23087185],
             [ 0.19565006],
             [ 0.20485527],
             [ 0.50279717],
             [ 0.2954391 ]])],
     [array([[ 0.09548894,  0.53021962, -0.42672835, -0.50085288, -0.21599975,
              -0.33332495,  0.40747684,  0.38345247, -0.03781623, -0.46857085,
               0.48999769, -0.12949857,  0.00157623, -0.51861862,  0.56025922,
               0.25729079],
             [ 0.28693035, -0.19004721,  0.26443327,  0.49889261,  0.19942085,
              -0.55211723, -0.00313824,  0.47261736,  0.26253592, -0.36673402,
               0.03903981, -0.06636791, -0.09100776,  0.04003322, -0.00215489,
              -0.46196124]]),
      array([[-0.06029299,  0.33177713,  0.03045518, -0.03056958,  0.3530096 ,
               0.33395246,  0.25263993,  0.41108909,  0.31403316, -0.16984653,
               0.19561492, -0.07190688,  0.04729751,  0.23527047, -0.14877131,
              -0.11405634],
             [-0.00412071, -0.25246125,  0.15343594, -0.1796721 ,  0.33726679,
               0.24812948,  0.41324933, -0.15769376, -0.00898528,  0.02820297,
              -0.41983795,  0.34757077, -0.41878585,  0.34349578,  0.36498868,
               0.40445092],
             [-0.16590573,  0.36024378, -0.17540811,  0.0474943 ,  0.38974418,
              -0.35510064, -0.15621793, -0.24059402, -0.13732092,  0.01605381,
               0.28447257,  0.03180725,  0.03169547,  0.3279157 , -0.38471678,
              -0.1892048 ],